config/routes.rb
Rails.application.routes.draw do
  resources :bands do
    resources :events, only: [:new, :create]
  end

  resources :bands do
    resources :band_reviews, only: [:new, :create]
    resources :band_favs, only: [:create]
  end

  resources :bars, only: [:index, :show] do
    resources :bar_favs, only: [:create]
  end

  resources :events, except: [:new, :create] do
    resources :participations, only: [ :create ]
  end

  resources :band_reviews, only: :destroy
  resources :bar_favs, only: :destroy
  resources :band_favs, only: :destroy
  resources :participations, only: :destroy
  devise_for :users
  root to: 'pages#home'
end

app/models/bar.rb
class Bar < ApplicationRecord
  has_many :events, dependent: :destroy
  has_many :bar_favs, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many_attached :photo

  include PgSearch::Model
  pg_search_scope :global_search,
                  against: [:name, :description, :address],
                  using: { tsearch: { prefix: true } }
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def index
    @bars = Bar.all
    search = params[:search]
    @bars = Bar.global_search(search) if search.present?
    @markers = @bars&.geocoded&.map do |bar|
      {
        lat: bar.latitude,
        lng: bar.longitude,
        info_window: render_to_string(partial: "info_window", locals: { bar: bar })
      }
    end
  end

  def show
    @bar = Bar.find(params[:id])
    @events = @bar.events.future.sorted_by_date
  end
end

app/views/bars/index.html.erb
<div class="backlink">
  <%= link_to :back do %>
    <i class="fas fa-arrow-left"></i>
  <% end %>
</div>
<div class="container">
  <div class="event-title-container">
    <h1>les bars</h1>
  </div>
<%= render 'shared/bar_searchbar'%>
</div>

<div id="map"
     style="width: 100%; height: 100%;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/bars/show.html.erb
<div class="tainer">
  <div class="bar-show-banner" >
  <div class="backlink">
    <%= link_to :back do %>
      <i class="fas fa-arrow-left"></i>
    <% end %>
  </div>
    <div class="bar-show-title">
    <%# <img src="http://res.cloudinary.com/dvocm8ddc/image/upload/v1630415024/pncxgkwdwxypas5vcezj.png" id="bar_logo"> %>
      <h1><%= @bar.name %></h1>
    </div>
    <div class="bar-favorite">
      <% if current_user.bar_favs %>
        <% if current_user.bar_favs.where(bar_id: @bar.id).first %>
        <% @bar_fav = current_user.bar_favs.where(bar_id: @bar.id).first %>
          <%= link_to bar_fav_path(@bar_fav),
            method: :delete,
            remote: true,
            id: "remove-fav" do %>
            <div id="fav-icone"><i class="fas fa-star"></i></div>
            <% end %>
          <%# <div><i class="fas fa-star"></i></div> %>
        <% else %>
          <%= link_to bar_bar_favs_path(@bar), method: :post, remote: true, id: "add-fav" do %>
            <div id="fav-icone"><i class="far fa-star"></i></div>
        <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="bar-show-content">
    <div class="bar-show-photo">
      <% @bar.photo.each do |photo| %>
        <%= cl_image_tag photo.key, :width=>400, :height=>250, 'aria-expanded': false %>
      <% end %>
    </div>
    <div class="d-flex justify-content-center mb-4">
      <div class="btn btn-ghost">
        <%= @bar.description %>
      </div>
    </div>

    <div class="d-flex justify-content-center mb-4">
      <p><%= @bar.address %></p>
    </div>
    <div class="d-flex justify-content-center mb-4">
      <p><i class="far fa-clock"></i> <%= @bar.opening_time %></p>
    </div>
    <div class="d-flex justify-content-center mb-4">
      <div class="bar-show-programme">
        <% if @events.count > 1 %>
          <h2>Dates à venir</h2>
        <% elsif @events.count > 0 %>
          <h2>Date à venir</h2>
        <% else %>
          <h2>Pas de date à venir</h2>
        <% end %>
        <% @events.each do |event| %>
          <%=link_to "#{event.band.name} : #{event.start_date.strftime('%d/%m')} - #{event.start_date.strftime('%H:%M')}", event_path(event), class:"btn btn-gradient"  %>
        <%end%>
      </div>
    </div>
  </div>
</div>