config/routes.rb
Rails.application.routes.draw do
  resources :bands do
    resources :events, only: [:new, :create]
  end

  resources :bands do
    resources :band_reviews, only: [:new, :create]
    resources :band_favs, only: [:create]
  end

  resources :bars, only: [:index, :show] do
    resources :bar_favs, only: [:create]
  end

  resources :events, except: [:new, :create] do
    resources :participations, only: [ :create ]
  end

  resources :band_reviews, only: :destroy
  resources :bar_favs, only: :destroy
  resources :band_favs, only: :destroy
  resources :participations, only: :destroy
  devise_for :users
  root to: 'pages#home'
end

app/views/shared/_band_card.html.erb
<div class="card_band_home">
  <% band.photos.each do |photo| %>
  <%= cl_image_tag photo.key, :width=>400, :height=>250, 'aria-expanded': false %>
  <% end %>
  <%= link_to band.name, band_path(band.id), class:"band-name-home"%>
  <div class="card-infos_band_home">
    <div>
      <% band.styles.first(2).each do |style| %>
      <div class="card-bandstyle">
        <div class="btn btn-ghost-mini">
          <%= style.style_type %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_band_index_card.html.erb
<% band.photos.each do |photo| %>
<%= link_to band_path(band.id) do %>
<div class="band-index-card">
  <div class="band-index-image">
  <%= cl_image_tag photo.key, :width=>180, :height=>120, 'aria-expanded': false %>
  <% end %>
    <div class="band-index-card-name">
      <%= band.name %>
    </div>
    <div class="card-bandstyle-container">
    <% band.styles.each do |style| %>
    <div class="card-bandstyle">
      <div class="btn btn-ghost-micro">
        <%= style.style_type %>
      </div>
    </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_band_review_rating.html.erb
<div class="band-review-rating-container">
  <div class="band-review-rating">
    <% if @band.band_reviews.count > 0 %>
      <% rating = 0 %>
      <% @band.band_reviews.each do |review| %>
          <% rating += review.rating %>
        <% end %>
          <% averagerating = rating / @band.band_reviews.count %>
          <% averagerating.times do %>
          <div class="show-stars">
            <i class="fas fa-star"></i>
          </div>
      <% end %>
    <% end %>
  </div>
   <% if @band.band_favs.count > 0 %>
    <div class="band-likes">
      <%= @band.band_favs.count %>
      <i class="fas fa-heart"></i>
    </div>
  <% end %>
  <% if @band.band_reviews.count > 0 %>
  <div class="band-comment">
    <div class="band-comment-content">
      <%= @band.band_reviews.count %>
        <i class="fas fa-comment"></i>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_band_searchbar.html.erb
<hr>

<div class="event-search-form-container">
  <%= simple_form_for :search, method: "get" do |f| %>
  <div class="event-date-input" id="search_start_date">
    <%= f.input :band, as: :string, placeholder: "Par Artiste", required: false, class: "band-search-input", label: false %>
  </div>
  <div class="event-style-input" id="search_style_type">
    <%= f.input :band_style, collection: Style::STYLES.sort, label: false, input_html: { multiple: true } %>
  </div>
  <div class="event-serch-button-container">
    <%= f.button :submit, value: "Rechercher", class: "btn btn-ghost mt-2", id: "event-search-button" %>
  </div>
  <% end %>
</div>

app/views/shared/_bar_searchbar.html.erb
<div class="event-search-label">
  <div class="event-search-icone">
    <i class="fas fa-search"></i>
  </div>
  <h3>Rechercher</h3>
</div>
<div class="event-search-form-container">
  <%= simple_form_for :search, method: "get" do |f| %>
  <div class="bar-search-bar" id="bar-search-bar">
    <%= f.input :bar, as: :string, placeholder: "Nom, type...", required: false, label: false %>
  </div>
  <% end %>
</div>

app/views/shared/_event_card.html.erb
<div class="card-event">
  <div class="band-img" id="same-band-format">
    <%= cl_image_tag event.band.photos[0].key, :height=>150, :width=>270,'aria-expanded': false %>
  </div>
  <div class="event-time">
  <%=  "#{event.start_date.strftime('%d/%m')}" %>
  <br>
  <%= "#{event.start_date.strftime('%H:%M')}" %>
  </div>
    <div class="card-event-infos">
      <div>
        <%= link_to event.band.name, event_path(event.id) %>
        <br>x<br>
        <%= link_to event.bar.name, event_path(event.id) %>
      </div>
    </div>
    <div class="event-address">
      <%= event.bar.address %>
    </div>
</div>

app/views/shared/_event_searchbar.html.erb
<div class="event-search-label">
  <div class="event-search-icone">
    <i class="fas fa-search"></i>
  </div>
  <h3>Rechercher</h3>
</div>

<div class="event-search-form-container">
  <%= simple_form_for :search, method: "get" do |f| %>
  <div class="event-date-input" id="search_start_date">
    <%= f.input :date, as: :string, placeholder: "Par dates", required: false, input_html: {class: "datepicker"}, label: false %>
  </div>
  <div class="event-style-input" id="search_style_type">
    <%= f.input :style_type, placeholder: "Par style", collection: Style::STYLES.sort, prompt: "Par style" %>
  </div>
  <div class="event-serch-button-container">
    <%= f.button :submit, value: "Rechercher", class: "btn btn-ghost", id: "event-search-button" %>
  </div>
  <% end %>
</div>

app/views/shared/_fav_bar_home.html.erb
<%# <h4 id="best-bar-title" >Mes bars préférés</h4> %>
<div class="cards-best-bar-container">
  <% if current_user && current_user.bar_favs %>
    <% @bar_favs = current_user.bar_favs %>
    <% @bar_favs.each do |bar_fav| %>
      <% bar = Bar.find(bar_fav.bar_id) %>
       <div class="card-best-bar">
        <div class="card-best-photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)">
          <% bar.photo.each do |photo| %>
          <%= cl_image_tag photo.key, :width=>400, :height=>250, 'aria-expanded': false %>
          <% end %>
          <%= link_to bar.name, bar_path(bar.id), class: "bar-name" %>
          <% if bar.events.count > 0 %>
            <div class="best_bar_event-count">
              <%= bar.events.count %>
            </div>
          <% end %>
        </div>
      </div>
        <% end %>
        <% end %>
      </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<nav class="header">
	<div class="header__item <%= "header__item--active" if controller_name == "pages" && action_name == "home" %>">
    <a href="/">
		<div class="header__item-content">
			<img src="http://res.cloudinary.com/dvocm8ddc/image/upload/v1629902563/yznpbp3kj6ipqrojfyfd.png" class="navbar-logo">
			<%# <span>Accueil</span> %>
		</div>
    </a>
	</div>

	<div class="header__item <%= "header__item--active" if controller_name == "bands" && action_name == "index"%>">
		<div class="header__item-content">
    <a href="/bands">
      <img src="http://res.cloudinary.com/dvocm8ddc/image/upload/v1629902667/nrzzhevfcqofigtu1akv.png" class="navbar-logo">
		</div>
    </a>
	</div>
	<div class="header__item <%= "header__item--active" if controller_name == "events" && action_name == "index" %>">
    <a href="/events">
		<div class="header__item-content">
      <img src="http://res.cloudinary.com/dvocm8ddc/image/upload/v1629902689/xruqwo2ns5utxlkaj9fr.png" class="navbar-logo">
			<%# <span>Evenements</span> %>
		</div>
    </a>
	</div>

	<div class="header__item <%= "header__item--active" if controller_name == "registrations" && action_name == "edit" %>">
    <a href="/users/edit">
		<div class="header__item-content">
      <img src="http://res.cloudinary.com/dvocm8ddc/image/upload/v1629902700/wyryn2zwcvkkyfskrgao.png" class="navbar-logo">
        <%# <span>Profil</span> %>
      </div>
  </div>
  </a>
</div>
</nav>

app/views/shared/_paticipation_popup.html.erb
<div class="participation-popup-cont">
  <div id="participation-popup" class="hidden">
  <div id="participation-popup-close">
    <i class="far fa-times-circle"></i>
  </div>
    <h2><%= @event.name %> ajouté à vos évenements!</h2>
  </div>
</div>

app/views/shared/_review.html.erb
<div class="reviews-container">
  <h3><%= "Avis sur #{@band.name}" %></h3>
    <% @band.band_reviews.each do |band_review| %>
    <div class="band-review">
      <div id="reviews" class="band-review-content">
        <% @user = User.find(band_review.user_id) %>
        <div class="band-review-content-name"><%= "@#{@user.nickname} : " %></div>
        <div class="band-review-content-comment"><%= band_review.comment %></div>
      </div>
      <div class="band-review-rating">
        <% stars = band_review.rating  %>
        <% stars.times do %>
        <div class="show-stars">
          <i class="fas fa-star"></i>
        </div>
        <% end %>
        <% if band_review.user_id == current_user.id %>
          <div class="band-review-delete">
          <%= link_to band_review_path(band_review.id), method: :delete, remote: true do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
</div>