config/routes.rb
Rails.application.routes.draw do
  resources :bands do
    resources :events, only: [:new, :create]
  end

  resources :bands do
    resources :band_reviews, only: [:new, :create]
    resources :band_favs, only: [:create]
  end

  resources :bars, only: [:index, :show] do
    resources :bar_favs, only: [:create]
  end

  resources :events, except: [:new, :create] do
    resources :participations, only: [ :create ]
  end

  resources :band_reviews, only: :destroy
  resources :bar_favs, only: :destroy
  resources :band_favs, only: :destroy
  resources :participations, only: :destroy
  devise_for :users
  root to: 'pages#home'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :band
  has_many :styles, through: :band
  belongs_to :bar
  has_many :participations, dependent: :destroy
  validates :start_date, presence: true
  validates :bar_id, presence: true, uniqueness: { scope: :start_date }

  scope :future, -> { where(start_date: DateTime.now..2.years.from_now) }
  scope :sorted_by_date, -> { order(start_date: :asc) }

  include PgSearch::Model
  pg_search_scope :global_search,
                  against: [:start_date],
                  associated_against: {
                  styles: [:style_type]
                  },
                  using: { tsearch: { prefix: true } }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @event = Event.find(params[:id])
    @participations = Participation.where(user: current_user.id)
    @user = current_user
    @cal = AddToCalendar::URLs.new(
        start_datetime: @event.start_date,
        title: "#{@event.band.name}-#{@event.bar.name}",
        timezone: 'Europe/Paris'
      )
  end

  def index
    search = params[:search]
    if search.present?
      if search[:date].blank? && search[:style_type].blank?
        @events = Event.future.sorted_by_date
      elsif search[:date].blank? && search[:style_type].present?
        @events = Event.future.sorted_by_date.global_search(search[:style_type])
      elsif search[:date].present? && search[:style_type].blank?
        if date_search_length(params).length > 1
          enddate = create_end_date(params)
          startdate = create_start_date(params)
          nextevents = Event.future.sorted_by_date.where("start_date > ?", startdate )
          @events = nextevents.where("start_date < ?", enddate )
        else
          @events = Event.future.sorted_by_date.global_search(search[:date])
        end
      elsif search[:date].present? && search[:style_type].present?
        if date_search_length(params).length > 1
          enddate = create_end_date(params)
          startdate = create_start_date(params)
          nextevents = Event.future.sorted_by_date.where("start_date > ?", startdate )
          eventsbydate = nextevents.where("start_date < ?", enddate )
          bandstyle = Event.future.sorted_by_date.global_search(search[:style_type])
          @events = (eventsbydate & bandstyle)
        else
          eventsbydate = Event.future.sorted_by_date.global_search(search[:date])
          bandstyle = Event.future.sorted_by_date.global_search(search[:style_type])
          @events = (eventsbydate & bandstyle)
        end
      end
    else
      @events = Event.future.sorted_by_date
    end
        @bars = Bar.where(id: @events.pluck(:bar_id).uniq)
        @markers = @bars&.geocoded&.map do |bar|
      {
        lat: bar.latitude,
        lng: bar.longitude,
        info_window: render_to_string(partial: "info_window", locals: { bar: bar })
      }
    end
  end


  def new
    @band = Band.find(params[:band_id])
    @event = Event.new
  end

  # rubocop:disable Metrics/MethodLength
  def create
    @event = Event.new(event_params)
    @band = Band.find(params[:band_id])
    @event.band = @band
    bar = Bar.find_by_name(params[:event][:bar_id])
    @event.bar = bar
    @event.name = "#{@band.name} x #{bar.name}"
    if @event.save
      @band.fans.each do |user|
        NewEventMailer.event_email(user, @event).deliver_later
      end
      redirect_to event_path(@event)
    else
      render :new
    end
  end
  # rubocop:enable Metrics/MethodLength

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def date_search_length(params)
    daterange = params[:search][:date].split(" to ")
  end

  def create_end_date(params)
    daterange = params[:search][:date].split(" to ")
    return daterange[1]
  end


  def create_start_date(params)
    daterange = params[:search][:date].split(" to ")
    return daterange[0]
  end

  def event_params
    params.require(:event).permit(:start_date, :name, :description, :bar_id, :hour)
  end
end

app/views/events/_info_window.html.erb
<div class="carousel-container">
    <div class="carousel-wrapper">
      <div class="carousel">
        <div class="cards-event">
          <% bar.events.future.each do |event| %>
            <%= render 'shared/event_card', event: event %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<div class="backlink">
  <%= link_to :back do %>
    <i class="fas fa-arrow-left"></i>
  <% end %>
</div>
<div class="container">
  <div class="user-events-cotainer">
    <div class="event-title-container">
      <h1>evenements</h1>
    </div>
      <% participations = Participation.where(user_id: current_user.id) %>
      <% if participations.count > 0 %>
    <div class="my-event-container">
      <h4 id="my-events" >Mes évènements</h4>
    </div>
    <div class="bar-show-programme">
      <% participations.each do |participation| %>
      <div class="btn btn-gradient participation-event-picture">
        <%= cl_image_tag participation.event.band.photos.first.key, class: "picture-of-band" %>
        <div class="blur-grayscale">
        </div>
        <div class="description-of-participation">
          <div>
            <%=link_to participation.event.name, event_path(participation.event) %>
            <%= " le #{participation.event.start_date.strftime('%d/%m')} à #{participation.event.start_date.strftime('%H:%M')} " %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

<%= render 'shared/event_searchbar'%>

  <% today = [] %>
  <% others = [] %>
  <% @events.each do |event| %>
    <% if event.start_date.today? %>
      <% today << event %>
    <% else %>
      <% others << event %>
    <% end %>
  <% end %>
  <% if today.count > 0 %>
  <h2>Aujourd'hui</h2>
  <% end %>
  <div class="carousel-container">
    <div class="carousel-wrapper">
      <div class="carousel">
        <div class="cards-event">
        <% today.each do |event| %>
          <%= render 'shared/event_card', event: event %>
        <% end %>
        </div>
      </div>
    </div>
  </div>

<% if others.count > 0 %>
 <h2>Prochainement</h2>
<% elsif others.count < 1 && today.count > 0 %>
  <h2></h2>
<% else %>
  <h2 style="text-align: center;">Pas de résultats pour cette recherche</h2>
<% end %>
      <div class="carousel">
        <div class="cards-event">
        <% others.each do |event| %>
        <%= render 'shared/event_card', event: event %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="up-container">
  <div class="up-icone" id="up-button">
    <i class="fas fa-arrow-up"></i>
  </div>
</div>

<div id="map"
     style="width: 100%; height: 90%;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/events/new.html.erb
<div class="backlink">
  <%= link_to :back do %>
    <i class="fas fa-arrow-left"></i>
  <% end %>
</div>
<div class="container">
  <h2>Créer mon évènement<h2>
  <%= simple_form_for [ @band, @event ] do |f| %>
    <div class="form-inputs">
      <%= f.datetime_field :start_date,
                  as: :date,
                  label: "Dâte de début",
                  input_html: { autocomplete: "start_date" }%>
      <%= f.input :description,
                  label: "Description de l'évènement",
                  input_html: { autocomplete: "description" }%>
      <%= f.input :bar_id, collection: Bar.all.map{|bar| bar.name}%>
    </div>
    <hr>
    <div class="form-actions">
      <%= f.button :submit, "Créer", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="backlink" >
  <%= link_to :back do %>
    <i class="fas fa-arrow-left"></i>
  <% end %>
</div>
<div class="event-show-title">
  <img src="http://res.cloudinary.com/dvocm8ddc/image/upload/v1629902689/xruqwo2ns5utxlkaj9fr.png" class="navbar-logo">
  <%= link_to @event.band.name, band_path(@event.band.id) %> <br> x <br>
  <%= link_to @event.bar.name, bar_path(@event.bar.id)  %>
  <div class="event-participation">
    <%  @participations = Participation.where(user: current_user.id)  %>
    <% if @participations.find_by_event_id(@event) %>
      <% @participation = @participations.find_by_event_id(@event) %>
            <%= link_to participation_path(@participation),
              method: :delete,
              remote: true,
              id: "remove-part" do %>
              <div id="part-icone"><i class="fas fa-calendar"></i></div>
              <% end %>
          <% else %>
            <%= link_to event_participations_path(@event.id), method: :post, remote: true, id: "add-part" do %>
              <div id="part-icone"><i class="far fa-calendar"></i></div>
          <% end %>
        <% end %>
      </div>
</div>
<div class="container">

<div class="infos-event">
  <%= "#{@event.start_date.strftime('%d/%m')} - #{@event.start_date.strftime('%H:%M')} @ #{@event.bar.address}" %>
</div>

<%= render 'shared/paticipation_popup', event: @event %>

<div id="infos-container" class="container">

<%if @event.bar.photo.attached? %>
    <div class="carousel-container">
      <div id="carousel-event-wrapper">
        <div class="carousel">
          <div id="photos-event">
              <div class="photo-event">
                <% @event.bar.photo.each do |photo| %>
                  <%= cl_image_tag photo.key, :width=>400, :height=>250, 'aria-expanded': false %>
                <% end %>
              </div>
              <div class="photo-event">
                <% @event.band.photos.each do |photo| %>
                 <%= cl_image_tag photo.key, :width=>400, :height=>250, 'aria-expanded': false %>
                <% end %>
              </div>
          </div>
        </div>
      </div>
    </div>
<% end %>


<div class="d-flex justify-content-center mb-4">
  <% @event.band.styles.each do |style| %>
  <div class="bandstyle">
    <div class="btn btn-ghost">
      <%= link_to style.style_type, bands_path(search: {band_style: style.style_type}) %>
    </div>
  </div>
  <% end %>
</div>

<div class="description-event">
  <% if @event.description? %>
    <p><%= @event.description %></p>
  <% else %>
    <p><%= @event.band.description %></p>
  <% end %>
</div>
<div class="participants-count">
  <% if @event.participations.count > 1 %>
    <p><%= @event.participations.count %> personnes interessées par cet évenement.</p>
  <% elsif @event.participations.count == 1 %>
    <p><%= @event.participations.count %> personne interessée par cet évenement.</p>
  <% else %>
    <p>Soyez la première personne à vous inscrire à cet évenement!</p>
  <% end %>
</div>

<%= link_to "Ajouter au calendrier", @cal.google_url, id: "calendar-link", class: "d-none" %>

<div class="d-flex justify-content-center mb-4">
  <div id="event-location" class="links-event"> <%=link_to "", "https://www.google.fr/maps/dir//#{@event.bar.address}", class:"fas fa-map-marker-alt", style: "color:white" %></div>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>