config/routes.rb
Rails.application.routes.draw do
  resources :bands do
    resources :events, only: [:new, :create]
  end

  resources :bands do
    resources :band_reviews, only: [:new, :create]
    resources :band_favs, only: [:create]
  end

  resources :bars, only: [:index, :show] do
    resources :bar_favs, only: [:create]
  end

  resources :events, except: [:new, :create] do
    resources :participations, only: [ :create ]
  end

  resources :band_reviews, only: :destroy
  resources :bar_favs, only: :destroy
  resources :band_favs, only: :destroy
  resources :participations, only: :destroy
  devise_for :users
  root to: 'pages#home'
end

app/models/band.rb
class Band < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: :user_id
  has_many :events
  has_many :band_favs, dependent: :destroy
  has_many :fans, through: :band_favs, source: :user
  validates :name, presence: true, uniqueness: true
  has_many_attached :photos
  has_many :band_styles, dependent: :destroy
  has_many :styles, through: :band_styles
  has_many :band_reviews

  include PgSearch::Model
  pg_search_scope :global_search,
                  against: [ :name, :description ],
                  using: { tsearch: { prefix: true } }

  pg_search_scope :style_search,
                  associated_against: {
                    styles: [ :style_type ]
                  },
                  using: { tsearch: { prefix: true, any_word: true } }
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    if default_search?
      @bands = Band.all
    else
      bands_from_name = Band.global_search(search_band)
      bands_from_style = Band.style_search(search_style)
      @bands = [bands_from_name, bands_from_style].reject(&:blank?).reduce(:&)
      @bands ||= []
      @results = search_style
    end
  end

  def show
    @band_review = BandReview.new
    @band = Band.find(params[:id])
    @band_fav = BandFav.find_by(user: current_user, band: @band)
    @events = @band.events.future.sorted_by_date
    @band_reviews = @band.band_reviews
    @average_rating = @band_reviews.average(:rating)
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    @band.owner = current_user
    if @band.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    @band.update(band_params)
    redirect_to bands_path
  end

  private

  def default_search?
    params[:search].blank? || (search_band.blank? && search_style.blank?)
  end

  def search_style
    if params[:search][:band_style].is_a?(Array)
      params[:search][:band_style].compact_blank
    else
      params[:search][:band_style]
    end
  end

  def search_band
    params[:search][:band]
  end

  def band_params
    params.require(:band).permit(:name, :description, :style, :facebook_url, :youtube_url, photos: [])
  end
end

app/views/bands/edit.html.erb
<div class="form-container">
  <h2>Modifier mes informations<h2>
  <%= simple_form_for(@band) do |f| %>
    <div class="form-inputs">
      <%= f.input :name,
                  required: true,
                  label: "Nom du groupe",
                  input_html: { autocomplete: "name" } %>
      <%= f.input :style,
                  required: true,
                  collection: ["Rock", "Rap", 'Punk'], prompt: "Quel est ton style de musique?"%>
      <%= f.input :description,
                  label: "Description du groupe",
                  input_html: { autocomplete: "description" }%>
      <%= f.input :youtube_url,
                  input_html: { autocomplete: "youtube_url" }%>
      <%= f.input :facebook_url,
                  input_html: { autocomplete: "facebook_url" } %>
      <%= f.input :photos, as: :file,
                  input_html: { multiple: true } %>
    </div>
    <hr>
    <div class="form-actions">
      <%= f.button :submit, "Créer", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/bands/index.html.erb
<div class="backlink">
  <%= link_to :back do %>
    <i class="fas fa-arrow-left"></i>
  <% end %>
</div>
<div class="container">
  <div id="band-index-title"><h1>decouvrez des artistes</h1></div>

  <%= render 'shared/band_searchbar'%>

<% if @results.is_a?(Array)  %>
  <% @results.each do |style| %>
    <div class="results-style btn btn-ghost-micro"><%= style %></div>
  <% end %>
  <% elsif if @results.is_a?(String) %>
    <div class="results-style btn btn-ghost-micro"><%= @results %></div>
<% end %>

<% end %>

<% if @bands.count < 1 %>
  <h2 style="text-align: center;">Pas de résultat pour cette recherche</h2>
<% end %>

</div>
  <div class="card-band-container">
          <% @bands.each do |band| %>
          <%= render 'shared/band_index_card', band: band %>
          <% end %>
  </div>

app/views/bands/new.html.erb
<div class="container">
  <h2>Créer mon groupe de musique<h2>
  <%= simple_form_for(@band) do |f| %>
    <div class="form-inputs">
      <%= f.input :name,
                  required: true,
                  label: "Nom du groupe",
                  input_html: { autocomplete: "Nom du groupe" } %>
      <%= f.input :style,
                  required: true,
                  collection: ["Rock", "Rap", 'Punk'], prompt: "Quel est ton style de musique?"%>
      <%= f.input :description,
                  label: "Description du groupe",
                  input_html: { autocomplete: "description" }%>
      <%= f.input :youtube_url,
                  label: "Page Youtube",
                  input_html: { autocomplete: "youtube_url" }%>
      <%= f.input :facebook_url,
                  label: "Page Facebook",
                  input_html: { autocomplete: "facebook_url" } %>
      <%= f.input :photos, as: :file,
                  input_html: { multiple: true } %>
    </div>
    <hr>
    <div class="form-actions">
      <%= f.button :submit, "Créer", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/bands/show.html.erb
<div class="backlink">
  <%= link_to :back do %>
    <i class="fas fa-arrow-left"></i>
  <% end %>
</div>
<div class="d-flex align-items-top justify-content-between px-4" id="header-band">
  <h1><i class="fas fa-headphones"></i> <%= @band.name %></h1>
<div class="band-favorite">
      <% if current_user.favorite_bands.include? @band %>
          <%= link_to band_fav_path(@band_fav.id),
            method: :delete,
            remote: true,
            id: "remove-fav" do %>
            <div id="fav-icone"><i class="fas fa-heart"></i></div>
            <% end %>
        <% else %>
          <%= link_to band_band_favs_path(@band), method: :post, remote: true, id: "add-fav" do %>
            <div id="fav-icone"><i class="far fa-heart"></i></div>
        <% end %>
      <% end %>
    </div>
</div>

<div class="bar-show-photo">
  <%= cl_image_tag @band.photos[0].key, :height=>250, 'aria-expanded': false%>
</div>

  <%= render 'shared/band_review_rating', band: @band %>

<div class="bandstyle-container">
<% @band.styles.each do |style| %>
<div class="bandstyle">
  <div class="btn btn-ghost">
    <%= link_to style.style_type, bands_path( search: {band_style: style.style_type}) %>
  </div>
</div>
<% end %>
</div>

<div class="card-bar-content">
  <p class="text-center"><%= @band.description %></p>
</div>

<% if @band.youtube_url %>
  <div class="youtube-video">
    <iframe width="360" height="203" src = "<%=@band.youtube_url%>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen class="mb-4"></iframe>
  </div>
<% end %>

<div id="band-show-program-title">
  <% if @events.present? && @events.count > 1 %>
  <h3>Prochains concerts : </h3>
  <% elsif @events.present? && @events.count == 1 %>
  <h3>Prochain concert : </h3>
  <% else %>
  <h3>En concert prochainement.</h3>
  <% end %>
</div>
<div class="band-show-program">
  <% @events.first(3).each do |event| %>
    <%=link_to "@#{event.bar.name} : #{event.start_date.strftime('%d/%m')} - #{event.start_date.strftime('%H:%M')}", event_path(event), class: "btn btn-gradient"%>
  <% end %>
</div>


  <%= render 'shared/review', band: @band %>

  <% reviews = BandReview.where(band_id: @band.id) %>
  <% unless reviews.find_by_user_id(current_user.id) || @band.owner == current_user%>
    <div id="comment-anchor" class="add-comment">
      <i class="fas fa-pen"></i><%= link_to "Ajouter un commentaire", new_band_band_review_path(@band) %>
    </div>
  <% end %>

app/views/bands/update.html.erb
<h1>Bands#update</h1>
<p>Find me in app/views/bands/update.html.erb</p>